version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: checkin-postgresdb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: checkin_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/migrations:/docker-entrypoint-initdb.d
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - checkin-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: checkin-app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: checkin_db
      DB_SSLMODE: disable
      SERVER_ADDR: :8080
    ports:
      - "8080:8080"
    stdin_open: true
    tty: true
    restart: unless-stopped
    networks:
      - checkin-network
networks:
  checkin-network:
    driver: bridge

volumes:
  postgres_data:
    name: checkin-postgres-data